#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
# 防止重复启动
[ -f /var/lock/overwall.lock -a $A = N ] && exit 1
LOCK=/var/lock/overwall-update.lock
[ -f $LOCK ] && exit 1
touch $LOCK
DIR=/usr/share/overwall
TMP=/tmp/overwall

log(){
	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/overwall.log
}

if [ $A = Y ];then
	mkdir -p $TMP
	while ! B=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/Lj2x16sRVDNJcuBv/lgtOgNsB/IwocS3gciO/HbAsESdvo3K0mI4);do
		sleep 2
	done
else
	B=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/Lj2x16sRVDNJcuBv/lgtOgNsB/IwocS3gciO/HbAsESdvo3K0mI4 || curl -Lfsm 9 https://raw.githubusercontent.com/Lj2x16sRVDNJcuBv/lgtOgNsB/master/IwocS3gciO/HbAsESdvo3K0mI4)
fi
[ -n "$B" ] && echo "$B" | base64 -d > /tmp/china.txt

if ! cmp -s /tmp/china.txt $TMP/china.txt;then
	log "Over Update  : Update China IP List"
	cp -f /tmp/china.txt $TMP/china.txt
	[ $A = N ] && ipset list china_v4 >/dev/null 2>&1 && $DIR/chinaipset
else
	log "Over Update  : China IPv4 List is up to date"
fi

C=$(uci -q get overwall.@global[0].run_mode)

if [ "$C" = router ];then
	if [ $A = Y ];then
		mkdir -p $TMP
		while ! D=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/Lj2x16sRVDNJcuBv/lgtOgNsB/IwocS3gciO/vY3PHj8qJmtTXg6);do
			sleep 2
		done
	else
		D=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/Lj2x16sRVDNJcuBv/lgtOgNsB/IwocS3gciO/vY3PHj8qJmtTXg6 || curl -Lfsm 9 https://raw.githubusercontent.com/Lj2x16sRVDNJcuBv/lgtOgNsB/master/IwocS3gciO/vY3PHj8qJmtTXg6)
	fi
	[ -n "$D" ] && echo "$D" | base64 -d > /tmp/china_v6.txt

	if ! cmp -s /tmp/china_v6.txt $TMP/china_v6.txt;then
		log "Over Update  : Update China IPv6 List"
		cp -f /tmp/china_v6.txt $TMP/china_v6.txt
		[ $A = N ] && ipset list china_v6 >/dev/null 2>&1 && $DIR/chinaipset v6
	else
		log "Over Update  : China IPv6 List is up to date"
	fi
fi

if [ "$C" = gfw -o "$(uci -q get overwall.@global[0].gfw_mode)" = 1 ];then
	if [ $A = Y ];then
		while ! curl -Lfsm 5 -o /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/Lj2x16sRVDNJcuBv/lgtOgNsB/IwocS3gciO/gVxoEuEit5EJeEm;do
			sleep 2
		done
	else
		curl -Lfso /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/Lj2x16sRVDNJcuBv/lgtOgNsB/IwocS3gciO/gVxoEuEit5EJeEm || curl -Lfso /tmp/gfw.b64 https://raw.githubusercontent.com/Lj2x16sRVDNJcuBv/lgtOgNsB/master/IwocS3gciO/gVxoEuEit5EJeEm
	fi
	$DIR/gfw
	if ! cmp -s /tmp/gfwnew.txt $TMP/gfw.list;then
		cp -f /tmp/gfwnew.txt $TMP/gfw.list
		log "Over Update  : Update GFW List"
		[ $A = N ] && /etc/init.d/overwall restart
	else
		log "Over Update  : GFW List is up to date"
	fi
fi
rm -f $LOCK /tmp/china*.txt /tmp/gfwnew.txt
[ $A = Y ] && /etc/init.d/overwall start &
